Dev mode
rpalakkal/teleport-rs pull request #26
Opened 2024-10-08 06:39 UTC by odysseus0

2024-10-08 15:34 UTC, amiller requested changes
Spent a little bit of time on it but theres lots of documentation changes and I'm not sure what substantive ones, I'd want to review them separately basically

2024-10-08 15:34 UTC, amiller commented on .gitignore
> +*.env
teleport.env should not be ignored since it contains public data to bake into the enclave

2024-10-08 15:34 UTC, amiller commented on Cargo.toml
> +axum-server = { version = "0.6.0", features = ["tls-rustls"] }
would prefer to review a separate PR for cosmetic changes just to keep the scope of changed files smaller

2024-10-08 15:34 UTC, amiller commented on docker-compose.yml
> +      - /dev/sgx_provision  # SGX provisioning device
these aren't adding info

2024-10-08 15:34 UTC, amiller commented on docs/ARCHITECTURE.md
> +# Teleport Architecture
I don't like using Gramine debug mode. Remote attestation etc is unavailable. I would rather just not use Gramine when running outside enclave

2024-10-16 13:56 UTC, amiller commented on src/twitter/mod.rs
> +    scheme: &Scheme,
this suggests there is some generality in the code for https/http. But given that http is only approprirate for development, it would be better to make this more conspicuous

2024-10-16 13:57 UTC, amiller commented on src/server_setup.rs
> +pub async fn setup_development_server(app: Router) -> Result<(), Box<dyn std::error::Error>> {
maybe it would be better to use https exclusively and inlcude a self-signed certificate you can use when developing and accessing localhost

2025-08-26 06:58 UTC, odysseus0 commented
Closing as no longer relevant

2025-08-26 06:58 UTC, closed without merging